sudo: false
language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install coveralls
  - pip install -e .[test]
script:
  - python -m py.test --cov=src/wagtailbakery --cov-report=xml tests/
after_success:
  - coveralls
