sudo: false
language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-django18
    - python: 2.7
      env: TOXENV=py27-django19
    - python: 2.7
      env: TOXENV=py27-django110
    - python: 2.7
      env: TOXENV=py27-django111
    - python: 3.5
      env: TOXENV=py35-django18
    - python: 3.5
      env: TOXENV=py35-django19
    - python: 3.5
      env: TOXENV=py35-django110
    - python: 3.5
      env: TOXENV=py35-django111
    - python: 3.6
      env: TOXENV=py36-django18
    - python: 3.6
      env: TOXENV=py36-django19
    - python: 3.6
      env: TOXENV=py36-django110
    - python: 3.6
      env: TOXENV=py36-django111
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install coveralls tox
script:
  - tox -e $TOXENV
after_success:
  - coveralls
